### ISSUE TITLE
Black square in Glance

### ISSUE THREAD

**Issue by Serbay350** [BleachDev/Rainy#5]
Hi, I'm using this app on my Vivoactive 5 and I noticed that there is a black square in the background of the glance. I tried to take a photo of it. 
Also, is there a reason the Location is in all uppercase? It's just personal taste, I personally would like it better in lowercase.

Other than that, I really like your app!

![PXL_20240418_093226743](https://github.com/BleachDev/Rainy/assets/42999037/b1cabef5-96c0-4d3d-b609-1466baa3ad59)

**Comment by BleachDev** [comment]
I'm not sure if its not possible on CIQ glances or if its a bug but i haven't found any way to get the background on a glance, its always just a black square.

For the name i chose uppercase because my Fenix 7 has glance titles in uppercase so it fits the best for that but some watches have it in lowercase so 🤷

I might redo the entire glance since it doesn't even vertically align properly (like on the image) on some devices.

**Comment by BleachDev** [comment]
Turns out i was wrong, fixed in https://github.com/BleachDev/Rainy/commit/78674a19ebe99d828da701f70617bdb680932742
